name: Build and Publish

on:
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.18)'
        required: true
        type: string
      create_tag:
        description: 'Create git tag'
        required: true
        default: true
        type: boolean

# Permissions needed for pushing tags and packages
permissions:
  contents: write
  id-token: write # For PyPI trusted publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
      
      - name: Verify version matches
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION="${{ github.event.inputs.version }}"
          # Check version in markup.py
          MARKUP_VERSION=$(grep -o "__version__ = '[0-9.]*'" MarkupPy/markup.py | cut -d "'" -f 2)
          # Check version in pyproject.toml
          PYPROJECT_VERSION=$(grep -o 'version = "[0-9.]*"' pyproject.toml | cut -d '"' -f 2)
          
          echo "markup.py version: $MARKUP_VERSION"
          echo "pyproject.toml version: $PYPROJECT_VERSION"
          echo "Requested version: $VERSION"
          
          if [ "$MARKUP_VERSION" != "$VERSION" ] || [ "$PYPROJECT_VERSION" != "$VERSION" ]; then
            echo "::error::Version mismatch! Please ensure MarkupPy/markup.py and pyproject.toml both have version $VERSION"
            exit 1
          fi
      
      - name: Create Git tag
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.create_tag == 'true'
        run: |
          VERSION="${{ github.event.inputs.version }}"
          VERSION_TAG="v$VERSION"
          
          # Check if tag already exists
          if git tag | grep -q "^$VERSION_TAG$"; then
            echo "Tag $VERSION_TAG already exists"
          else
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag -a "$VERSION_TAG" -m "Version $VERSION release"
            git push origin "$VERSION_TAG"
            echo "Created and pushed tag $VERSION_TAG"
          fi
      
      - name: Build package
        run: python -m build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 